// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demo.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, team_id, email, name, avatar_url)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, name, avatar_url, team_id, is_active, created_at, upated_at
`

type CreateUserParams struct {
	ID        string         `json:"id"`
	TeamID    string         `json:"team_id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.TeamID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, name, avatar_url, team_id, is_active, created_at, upated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpatedAt,
	)
	return i, err
}

const getUsersInTeam = `-- name: GetUsersInTeam :many
SELECT id, email, name, avatar_url, team_id, is_active, created_at, upated_at FROM users
WHERE team_id = ?
`

func (q *Queries) GetUsersInTeam(ctx context.Context, teamID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersInTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
